version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  build:
    commands:
      - echo "Building Lambda package..."
      - zip function.zip main.py
      # install matplotlip
      - mkdir package
      - pip install matplotlib -t package/
      - cp report.py package/
      - cd package
      - zip -r ../report.zip .
      - cd ..

      - echo "Uploading package..."
      - aws s3 cp function.zip s3://$DEPLOYMENT_BUCKET/function.zip
      - aws s3 cp report.zip s3://$DEPLOYMENT_REPORT_BUCKET/report.zip

      - echo "Updating Lambda..."
      - echo $LAMBDA_NAME
      - echo $DEPLOYMENT_BUCKET
      - aws --version
      - aws lambda update-function-code --function-name $LAMBDA_NAME --s3-bucket $DEPLOYMENT_BUCKET --s3-key function.zip
      - aws lambda update-function-code --function-name $LAMBDA_REPORT_NAME --s3-bucket $DEPLOYMENT_REPORT_BUCKET --s3-key report.zip

artifacts:
  files:
    - function.zip
    - report.zip