Resources:
  lambdaDeployment:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-lambda-code-deployment
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  lambdaDeploymentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref lambdaDeployment
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt lambdaDeployment.Arn
              - !Sub ${lambdaDeployment.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
  lambdaReportDeployment:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-lambda-report-deployment
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  lambdaReportDeploymentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref lambdaReportDeployment
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt lambdaReportDeployment.Arn
              - !Sub ${lambdaReportDeployment.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
  input:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-input-csv
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      #
      # STEP 3
      #
      # NotificationConfiguration:
      #   LambdaConfigurations:
      #     - Event: s3:ObjectCreated:*
      #       Function: !GetAtt lambdaTransformation.Arn
  inputBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref input
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt input.Arn
              - !Sub ${input.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
  output:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-output-parquet
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      #
      # STEP 3
      #
      # NotificationConfiguration:
      #   LambdaConfigurations:
      #     - Event: s3:ObjectCreated:*
      #       Function: !GetAtt lambdaReport.Arn
      #       Filter:
      #         S3Key:
      #           Rules:
      #             - Name: prefix
      #               Value: parquet/
  outputBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref output
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt output.Arn
              - !Sub ${output.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
  report:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-report
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  reportBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref report
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt report.Arn
              - !Sub ${report.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
  #
  # STEP 2 with upload of zip
  #

  # lambdaExecutionRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: lambda.amazonaws.com
  #           Action: sts:AssumeRole
  #     Policies:
  #       - PolicyName: S3AccessPolicy
  #         PolicyDocument:
  #           Statement:
  #             - Effect: Allow
  #               Action:
  #                 - s3:GetObject
  #               Resource: '*'
  #               # Resource: !Sub ${input.Arn}/*
  #             - Effect: Allow
  #               Action:
  #                 - s3:PutObject
  #               Resource: '*'
  #               # Resource: !Sub ${output.Arn}/*
  #             - Effect: Allow
  #               Action:
  #                 - logs:CreateLogGroup
  #               Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
  #             - Effect: Allow
  #               Action:
  #                 - logs:CreateLogStream
  #                 - logs:PutLogEvents
  #               Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*
  # lambdaTransformation:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     FunctionName: !Sub ${AWS::StackName}-csv-to-parquet
  #     Runtime: python3.11
  #     Handler: main.lambda_handler
  #     Role: !GetAtt lambdaExecutionRole.Arn
  #     Code:
  #       S3Bucket: !Ref lambdaDeployment
  #       S3Key: function.zip
  #     MemorySize: 1024
  #     Timeout: 120
  #     Layers:
  #       - arn:aws:lambda:eu-central-1:336392948345:layer:AWSSDKPandas-Python311:31
  #     Environment:
  #       Variables:
  #         OUTPUT_BUCKET: !Ref output
  # LambdaInvokePermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: lambda:InvokeFunction
  #     FunctionName: !Ref lambdaTransformation
  #     Principal: s3.amazonaws.com
  #     SourceArn: !GetAtt input.Arn
  # lambdaReport:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     FunctionName: !Sub ${AWS::StackName}-parquet-to-report
  #     Runtime: python3.11
  #     Handler: report.lambda_handler
  #     Role: !GetAtt lambdaExecutionRole.Arn
  #     Code:
  #       S3Bucket: !Ref lambdaReportDeployment
  #       S3Key: report.zip
  #     MemorySize: 1024
  #     Timeout: 120
  #     Layers:
  #       - arn:aws:lambda:eu-central-1:336392948345:layer:AWSSDKPandas-Python311:31
  #     Environment:
  #       Variables:
  #         REPORT_BUCKET: !Ref report
  # LambdaInvokePermissionReport:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: lambda:InvokeFunction
  #     FunctionName: !Ref lambdaReport
  #     Principal: s3.amazonaws.com
  #     SourceArn: !GetAtt output.Arn
  #
  # END STEP 2
  #
  #
  # Repository Connection for CI/CD
  #
  #
  # STEP 4 -> Authorize Connection
  #
  # GitHubConnection:
  #   Type: AWS::CodeStarConnections::Connection
  #   Properties:
  #     ConnectionName: !Sub ${AWS::StackName}-github-connection
  #     ProviderType: GitHub

  # PipelineRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: codepipeline.amazonaws.com
  #           Action: sts:AssumeRole

  #     Policies:
  #       - PolicyName: PipelinePolicy
  #         PolicyDocument:
  #           Version: '2012-10-17'
  #           Statement:

  #             - Effect: Allow
  #               Action:
  #                 - codestar-connections:UseConnection
  #               Resource: '*'

  #             - Effect: Allow
  #               Action:
  #                 - codebuild:StartBuild
  #                 - codebuild:BatchGetBuilds
  #               Resource: '*'

  #             - Effect: Allow
  #               Action:
  #                 - s3:PutObject
  #                 - s3:GetObject
  #               Resource: '*'

  #             - Effect: Allow
  #               Action:
  #                 - lambda:UpdateFunctionCode
  #                 - lambda:GetFunction
  #                 - lambda:GetFunctionConfiguration
  #                 - lambda:UpdateFunctionConfiguration
  #                 - lambda:PublishVersion
  #               Resource: '*'

  #             - Effect: Allow
  #               Action:
  #                 - logs:CreateLogGroup
  #                 - logs:CreateLogStream
  #                 - logs:PutLogEvents
  #               Resource: '*'

  # BuildRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: codebuild.amazonaws.com
  #           Action: sts:AssumeRole

  #     Policies:
  #       - PolicyName: CodeBuildPolicy
  #         PolicyDocument:
  #           Version: '2012-10-17'
  #           Statement:

  #             - Effect: Allow
  #               Action:
  #                 - logs:CreateLogGroup
  #                 - logs:CreateLogStream
  #                 - logs:PutLogEvents
  #               Resource: '*'

  #             - Effect: Allow
  #               Action:
  #                 - s3:PutObject
  #                 - s3:GetObject
  #                 - s3:ListBucket
  #               Resource: '*'

  #             - Effect: Allow
  #               Action:
  #                 - s3:PutObject
  #               Resource: !Sub ${lambdaDeployment.Arn}/*

  #             - Effect: Allow
  #               Action:
  #                 - lambda:UpdateFunctionCode
  #                 - lambda:GetFunction
  #               Resource: !GetAtt lambdaTransformation.Arn

  #             - Effect: Allow
  #               Action:
  #                 - lambda:UpdateFunctionCode
  #                 - lambda:GetFunction
  #               Resource: !GetAtt lambdaReport.Arn

  # LambdaBuildProject:
  #   Type: AWS::CodeBuild::Project
  #   Properties:
  #     Name: !Sub ${AWS::StackName}-lambda-build

  #     ServiceRole: !GetAtt BuildRole.Arn

  #     Artifacts:
  #       Type: CODEPIPELINE

  #     Environment:
  #       Type: LINUX_CONTAINER
  #       ComputeType: BUILD_GENERAL1_SMALL
  #       Image: aws/codebuild/standard:7.0
  #       EnvironmentVariables:
  #         - Name: DEPLOYMENT_BUCKET
  #           Value: !Ref lambdaDeployment
  #         - Name: LAMBDA_NAME
  #           Value: !Ref lambdaTransformation
  #         - Name: DEPLOYMENT_REPORT_BUCKET
  #           Value: !Ref lambdaReportDeployment
  #         - Name: LAMBDA_REPORT_NAME
  #           Value: !Ref lambdaReport

  #     Source:
  #       Type: CODEPIPELINE

  # LambdaPipeline:
  #   Type: AWS::CodePipeline::Pipeline
  #   Properties:
  #     RoleArn: !GetAtt PipelineRole.Arn

  #     ArtifactStore:
  #       Type: S3
  #       Location: !Ref lambdaDeployment

  #     Stages:

  #       - Name: Source
  #         Actions:
  #           - Name: GitHubSource
  #             ActionTypeId:
  #               Category: Source
  #               Owner: AWS
  #               Provider: CodeStarSourceConnection
  #               Version: '1'

  #             OutputArtifacts:
  #               - Name: SourceOutput

  #             Configuration:
  #               ConnectionArn: !Ref GitHubConnection
  #               FullRepositoryId: l3onh4rd/project-data-engineering
  #               BranchName: main

  #       - Name: Build
  #         Actions:
  #           - Name: BuildLambda
  #             ActionTypeId:
  #               Category: Build
  #               Owner: AWS
  #               Provider: CodeBuild
  #               Version: '1'

  #             InputArtifacts:
  #               - Name: SourceOutput

  #             OutputArtifacts:
  #               - Name: BuildOutput

  #             Configuration:
  #               ProjectName: !Ref LambdaBuildProject
  #
  # END STEP 4
  #
  #
  # AWS Glue Teil
  #
  #
  # STEP 5
  #
  # GlueDatabase:
  #   Type: AWS::Glue::Database
  #   Properties:
  #     CatalogId: !Ref AWS::AccountId
  #     DatabaseInput:
  #       Name: parquet_db

  # GlueTable:
  #   Type: AWS::Glue::Table
  #   Properties:
  #     DatabaseName: !Ref GlueDatabase
  #     CatalogId: !Ref AWS::AccountId

  #     TableInput:
  #       Name: parquet_table
  #       TableType: EXTERNAL_TABLE

  #       StorageDescriptor:
  #         Columns:
  #           - Name: id
  #             Type: int
  #           - Name: receipt_id
  #             Type: int
  #           - Name: street
  #             Type: string
  #           - Name: zipcode
  #             Type: int
  #           - Name: date
  #             Type: timestamp
  #           - Name: time
  #             Type: string
  #           - Name: product_name
  #             Type: string
  #           - Name: unit_price
  #             Type: double
  #           - Name: quantity
  #             Type: int
  #           - Name: total_price
  #             Type: double

  #         Location: !Sub s3://${output}/parquet/

  #         InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
  #         OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat

  #         SerdeInfo:
  #           SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe

  # AthenaWorkGroup:
  #   Type: AWS::Athena::WorkGroup
  #   Properties:
  #     Name: parquet-workgroup
  #     WorkGroupConfiguration:
  #       ResultConfiguration:
  #         OutputLocation: !Sub s3://${output}/athena-results/

# Outputs:

#   InputBucket:
#     Description: Input bucket for CSV files
#     Value: !Ref input

#   OutputBucket:
#     Description: Output bucket for Parquet files
#     Value: !Ref output

#   DeploymentBucket:
#     Description: Bucket containing the Lambda deployment package
#     Value: !Ref lambdaDeployment
  
#   DeploymentReportBucket:
#     Description: Bucket containing the Lambda deployment package
#     Value: !Ref lambdaReportDeployment

#   LambdaFunction:
#     Description: Lambda function name
#     Value: !Ref lambdaTransformation
  
#   LambdaReportFunction:
#     Description: Lambda function name
#     Value: !Ref lambdaReport